export interface Product {
  id: number
  title: string
  description: string
  price: string
  originalPrice?: string
  image: string
  alt: string
  rating: number
  reviews: number
  inStock: boolean
  isPopular: boolean
  isNew: boolean
  categoryId: string
  features: string[]
  benefits: string[]
  category: string
  dateAdded: string
  lastModified?: string
  addedTimestamp?: number
  isRecentlyAdded?: boolean
}

// Complete product catalog with all 73 products - this is the master list
export const defaultProducts: Product[] = [
  // Baby and Kids Products (70-73) - Most recent additions
  {
    id: 70,
    title: "Baby Comfort Seat with Character Design",
    description:
      "Premium baby comfort seat with adorable character design, perfect for helping babies sit up safely and comfortably.",
    price: "$50.00",
    image: "/images/baby-comfort-seat-blue.jpg",
    alt: "Baby comfort seat with cute character design in blue color",
    rating: 4.8,
    reviews: 15,
    inStock: true,
    isPopular: true,
    isNew: true,
    categoryId: "kids-gifts",
    features: ["Ergonomic design", "Character patterns", "Safety harness", "Easy to clean", "Portable"],
    benefits: [
      "Helps sitting development",
      "Safe seating",
      "Entertaining design",
      "Easy maintenance",
      "Travel-friendly",
    ],
    category: "Baby Furniture",
    dateAdded: "2024-02-15",
    addedTimestamp: Date.now() - 86400000,
    isRecentlyAdded: true,
  },
  {
    id: 71,
    title: "Yellow Baby Chair with Penguin Design",
    description: "Adorable yellow baby chair featuring a cute penguin character design with colorful striped accents.",
    price: "$18.00",
    image: "/images/yellow-baby-chair-penguin.jpg",
    alt: "Yellow baby chair with penguin character design and colorful stripes",
    rating: 4.6,
    reviews: 12,
    inStock: true,
    isPopular: false,
    isNew: true,
    categoryId: "kids-gifts",
    features: ["Soft plush construction", "Penguin design", "Colorful fabric", "Comfortable seating", "Washable cover"],
    benefits: ["Comfortable seating", "Visual development", "Easy maintenance", "Safe materials", "Nursery decoration"],
    category: "Baby Furniture",
    dateAdded: "2024-02-14",
    addedTimestamp: Date.now() - 172800000,
    isRecentlyAdded: true,
  },
  {
    id: 72,
    title: "Pink Animal Pattern Baby Bathtub",
    description: "Inflatable pink baby bathtub with cute farm animal patterns, designed for safe and fun bath time.",
    price: "$20.00",
    image: "/images/pink-baby-bathtub-animals.jpg",
    alt: "Pink inflatable baby bathtub with farm animal patterns",
    rating: 4.7,
    reviews: 18,
    inStock: true,
    isPopular: false,
    isNew: true,
    categoryId: "kids-gifts",
    features: ["Inflatable design", "Animal patterns", "Non-slip bottom", "Drain plug", "Compact storage"],
    benefits: ["Safe bathing", "Fun bath time", "Easy storage", "Prevents slipping", "Stimulates imagination"],
    category: "Baby Bath",
    dateAdded: "2024-02-13",
    addedTimestamp: Date.now() - 259200000,
    isRecentlyAdded: true,
  },
  {
    id: 73,
    title: "Christmas Plush Dog with Santa Hat",
    description:
      "Adorable small plush dog toy wearing a festive red Santa hat with snowflake patterns, perfect for holiday gifting.",
    price: "$2.00",
    image: "/images/christmas-plush-dog-toy.jpg",
    alt: "Small plush dog toy with red Santa hat and snowflake patterns",
    rating: 4.3,
    reviews: 45,
    inStock: true,
    isPopular: true,
    isNew: true,
    categoryId: "kids-gifts",
    features: ["Soft plush material", "Santa hat", "Snowflake patterns", "Compact size", "Holiday themed"],
    benefits: [
      "Perfect holiday gift",
      "Soft and cuddly",
      "Affordable stocking stuffer",
      "Safe for children",
      "Festive decoration",
    ],
    category: "Holiday Toys",
    dateAdded: "2024-02-12",
    addedTimestamp: Date.now() - 345600000,
    isRecentlyAdded: true,
  },

  // Baby Clothing and Care Sets (60-69)
  {
    id: 60,
    title: "Baby Teddy Bear Clothing Set",
    description:
      "Adorable baby clothing set featuring cute teddy bear designs, perfect for keeping your little one comfortable and stylish.",
    price: "$25.00",
    image: "/images/baby-teddy-clothing-set.jpg",
    alt: "Baby clothing set with teddy bear designs and soft materials",
    rating: 4.8,
    reviews: 32,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Soft cotton blend", "Teddy bear prints", "Multiple pieces", "Easy snap closures", "Machine washable"],
    benefits: ["Gentle on skin", "Cute designs", "Complete outfit", "Easy diaper changes", "Long-lasting quality"],
    category: "Baby Clothing",
    dateAdded: "2024-02-05",
  },
  {
    id: 61,
    title: "Panda Baby Clothing Collection",
    description:
      "Charming panda-themed baby clothing collection with soft materials and adorable panda character designs.",
    price: "$28.00",
    image: "/images/panda-baby-clothing-set.jpg",
    alt: "Panda-themed baby clothing collection with soft materials",
    rating: 4.7,
    reviews: 28,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Panda character theme",
      "Ultra-soft materials",
      "Coordinated pieces",
      "Comfortable fit",
      "Durable construction",
    ],
    benefits: [
      "Adorable panda designs",
      "Maximum comfort",
      "Mix and match",
      "Perfect for daily wear",
      "Great gift option",
    ],
    category: "Baby Clothing",
    dateAdded: "2024-02-04",
  },
  {
    id: 62,
    title: "Cartoon Baby Bedding Set",
    description:
      "Complete cartoon-themed baby bedding set with colorful characters and soft, breathable materials for peaceful sleep.",
    price: "$35.00",
    image: "/images/cartoon-baby-bedding-set.jpg",
    alt: "Cartoon-themed baby bedding set with colorful characters",
    rating: 4.9,
    reviews: 41,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Complete bedding set", "Cartoon characters", "Breathable fabric", "Hypoallergenic", "Easy care"],
    benefits: [
      "Fun nursery environment",
      "Better sleep",
      "Safe for sensitive skin",
      "Easy maintenance",
      "Complete solution",
    ],
    category: "Baby Bedding",
    dateAdded: "2024-02-03",
  },
  {
    id: 63,
    title: "Pink Duck Baby Care Set",
    description: "Delightful pink duck-themed baby care set including essential items for your baby's daily routine.",
    price: "$22.00",
    image: "/images/pink-duck-baby-set.jpg",
    alt: "Pink duck-themed baby care set with essential items",
    rating: 4.6,
    reviews: 24,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Duck character theme",
      "Multiple care items",
      "Pink color scheme",
      "Baby-safe materials",
      "Organized storage",
    ],
    benefits: [
      "Complete care solution",
      "Cute and functional",
      "Safe for daily use",
      "Easy organization",
      "Perfect baby shower gift",
    ],
    category: "Baby Care",
    dateAdded: "2024-02-02",
  },
  {
    id: 64,
    title: "Johnson's Baby Powder Classic",
    description: "Trusted Johnson's baby powder for keeping baby's skin dry, comfortable, and fresh all day long.",
    price: "$8.00",
    image: "/images/johnsons-baby-powder.jpg",
    alt: "Johnson's Baby Powder classic formula for baby care",
    rating: 4.5,
    reviews: 89,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Classic formula", "Talc-free option", "Gentle fragrance", "Moisture absorption", "Pediatrician tested"],
    benefits: ["Keeps skin dry", "Prevents diaper rash", "Trusted brand", "Gentle on skin", "Long-lasting freshness"],
    category: "Baby Care",
    dateAdded: "2024-02-01",
  },
  {
    id: 65,
    title: "Whale Baby Bedding Collection",
    description:
      "Ocean-themed whale baby bedding collection with soft blues and adorable whale characters for a peaceful nursery.",
    price: "$32.00",
    image: "/images/whale-baby-bedding-set.jpg",
    alt: "Ocean-themed whale baby bedding collection in soft blue colors",
    rating: 4.8,
    reviews: 36,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Whale ocean theme",
      "Soft blue colors",
      "Complete bedding set",
      "Comfortable materials",
      "Machine washable",
    ],
    benefits: [
      "Calming ocean atmosphere",
      "Restful sleep",
      "Easy to maintain",
      "Durable and long-lasting",
      "Perfect nursery decoration",
    ],
    category: "Baby Bedding",
    dateAdded: "2024-01-31",
  },
  {
    id: 66,
    title: "Animal Pattern Baby Socks",
    description:
      "Cute animal-patterned baby socks set with non-slip grips and soft, stretchy materials for growing feet.",
    price: "$12.00",
    image: "/images/animal-baby-socks.jpg",
    alt: "Animal-patterned baby socks with non-slip grips",
    rating: 4.4,
    reviews: 52,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Animal patterns", "Non-slip grips", "Stretchy fit", "Multiple pairs", "Soft cotton blend"],
    benefits: ["Keeps feet warm", "Prevents slipping", "Grows with baby", "Adorable designs", "Great value pack"],
    category: "Baby Accessories",
    dateAdded: "2024-01-30",
  },
  {
    id: 67,
    title: "Strawberry Cupcake Bedding",
    description:
      "Sweet strawberry cupcake themed bedding set with pink tones and delicious dessert designs for a cozy nursery.",
    price: "$30.00",
    image: "/images/strawberry-cupcake-bedding.jpg",
    alt: "Strawberry cupcake themed bedding set in pink tones",
    rating: 4.7,
    reviews: 29,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Cupcake dessert theme",
      "Pink color palette",
      "Soft comfortable fabric",
      "Complete bedding set",
      "Easy care materials",
    ],
    benefits: [
      "Sweet nursery theme",
      "Comfortable for baby",
      "Easy to wash",
      "Adorable dessert designs",
      "Perfect for little girls",
    ],
    category: "Baby Bedding",
    dateAdded: "2024-01-29",
  },
  {
    id: 68,
    title: "Whale Pattern Baby Blanket",
    description: "Soft whale-patterned baby blanket with ocean-inspired designs, perfect for swaddling and comfort.",
    price: "$18.00",
    image: "/images/whale-pattern-bedding.jpg",
    alt: "Soft whale-patterned baby blanket with ocean designs",
    rating: 4.6,
    reviews: 43,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Whale ocean patterns",
      "Ultra-soft material",
      "Perfect swaddling size",
      "Breathable fabric",
      "Machine washable",
    ],
    benefits: ["Comfort and warmth", "Perfect for swaddling", "Easy to clean", "Calming ocean theme", "Versatile use"],
    category: "Baby Blankets",
    dateAdded: "2024-01-28",
  },
  {
    id: 69,
    title: "Baby Feeding Essential Set",
    description:
      "Complete baby feeding set with bottles, utensils, and accessories for introducing solid foods safely.",
    price: "$24.00",
    image: "/images/baby-feeding-set.jpg",
    alt: "Complete baby feeding set with bottles and utensils",
    rating: 4.8,
    reviews: 67,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Complete feeding set",
      "BPA-free materials",
      "Age-appropriate utensils",
      "Easy-grip handles",
      "Dishwasher safe",
    ],
    benefits: [
      "Safe feeding transition",
      "Promotes self-feeding",
      "Easy to clean",
      "Durable construction",
      "Complete feeding solution",
    ],
    category: "Baby Feeding",
    dateAdded: "2024-01-27",
  },

  // Toys and Gifts (50-59)
  {
    id: 50,
    title: "Animal Boat Baby Blanket",
    description:
      "Adorable baby blanket featuring cute animals on boats, perfect for keeping your little one warm and cozy.",
    price: "$20.00",
    image: "/images/animal-boat-baby-blanket.jpg",
    alt: "Baby blanket with cute animals on boats design",
    rating: 4.5,
    reviews: 38,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Animal boat theme",
      "Soft plush material",
      "Machine washable",
      "Hypoallergenic fabric",
      "Perfect baby size",
    ],
    benefits: [
      "Warmth and comfort",
      "Safe for sensitive skin",
      "Easy to maintain",
      "Stimulates imagination",
      "Perfect for naptime",
    ],
    category: "Baby Blankets",
    dateAdded: "2024-01-26",
  },
  {
    id: 51,
    title: "Baby Shoes Collection",
    description:
      "Adorable collection of baby shoes in various colors and styles, perfect for first steps and special occasions.",
    price: "$15.00",
    image: "/images/baby-shoes-collection.jpg",
    alt: "Collection of baby shoes in various colors and styles",
    rating: 4.6,
    reviews: 54,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Multiple color options",
      "Soft sole construction",
      "Easy slip-on design",
      "Breathable materials",
      "Non-slip grip",
    ],
    benefits: [
      "Protects little feet",
      "Supports natural development",
      "Easy to put on",
      "Comfortable all-day wear",
      "Perfect for learning to walk",
    ],
    category: "Baby Shoes",
    dateAdded: "2024-01-25",
  },
  {
    id: 52,
    title: "Blue Bear Storage Chest",
    description:
      "Charming blue bear-themed storage chest perfect for organizing toys, clothes, and nursery essentials.",
    price: "$45.00",
    image: "/images/blue-bear-storage-chest.jpg",
    alt: "Blue bear-themed storage chest for nursery organization",
    rating: 4.7,
    reviews: 31,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Large storage capacity",
      "Bear character design",
      "Safety hinges",
      "Durable construction",
      "Easy to clean surface",
    ],
    benefits: [
      "Keeps nursery organized",
      "Safe for children",
      "Adds decorative element",
      "Long-lasting durability",
      "Encourages tidiness",
    ],
    category: "Storage Solutions",
    dateAdded: "2024-01-24",
  },
  {
    id: 53,
    title: "Happy Birthday Gift Bags",
    description: "Colorful happy birthday gift bags perfect for party favors and special birthday celebrations.",
    price: "$8.00",
    image: "/images/happy-birthday-gift-bags.jpg",
    alt: "Colorful happy birthday gift bags for party celebrations",
    rating: 4.3,
    reviews: 76,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "gifts",
    features: [
      "Festive birthday design",
      "Multiple sizes available",
      "Sturdy construction",
      "Bright colorful graphics",
      "Reusable material",
    ],
    benefits: [
      "Perfect for party planning",
      "Creates festive atmosphere",
      "Durable for multiple uses",
      "Eye-catching designs",
      "Great value pack",
    ],
    category: "Party Supplies",
    dateAdded: "2024-01-23",
  },
  {
    id: 54,
    title: "Green Plush Keychain",
    description: "Cute green plush keychain perfect as a small gift or accessory for bags and keys.",
    price: "$5.00",
    image: "/images/green-plush-keychain.jpg",
    alt: "Cute green plush keychain accessory",
    rating: 4.2,
    reviews: 89,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "gifts",
    features: [
      "Soft plush material",
      "Compact size",
      "Secure keyring attachment",
      "Vibrant green color",
      "Durable construction",
    ],
    benefits: [
      "Perfect small gift",
      "Easy to carry",
      "Adds personality to keys",
      "Soft and cuddly",
      "Affordable accessory",
    ],
    category: "Accessories",
    dateAdded: "2024-01-22",
  },
  {
    id: 55,
    title: "Red Rose Bouquet Display",
    description: "Beautiful artificial red rose bouquet display, perfect for home decoration and lasting beauty.",
    price: "$35.00",
    image: "/images/red-rose-bouquet-display.jpg",
    alt: "Beautiful artificial red rose bouquet display",
    rating: 4.8,
    reviews: 42,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "home-decor",
    features: [
      "Realistic artificial roses",
      "Long-lasting beauty",
      "No maintenance required",
      "Elegant arrangement",
      "Suitable for any room",
    ],
    benefits: [
      "Permanent floral beauty",
      "No watering needed",
      "Allergy-friendly option",
      "Cost-effective decoration",
      "Always looks fresh",
    ],
    category: "Home Decor",
    dateAdded: "2024-01-21",
  },
  {
    id: 56,
    title: "Purple Flower Bouquet Display",
    description: "Elegant purple flower bouquet display with mixed blooms, perfect for adding color to any space.",
    price: "$32.00",
    image: "/images/purple-flower-bouquet-display.jpg",
    alt: "Elegant purple flower bouquet display with mixed blooms",
    rating: 4.6,
    reviews: 35,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "home-decor",
    features: [
      "Mixed purple flowers",
      "Artificial long-lasting blooms",
      "Professional arrangement",
      "Vibrant purple tones",
      "Maintenance-free",
    ],
    benefits: [
      "Adds elegant color",
      "No care required",
      "Perfect for any season",
      "Brightens living spaces",
      "Great conversation piece",
    ],
    category: "Home Decor",
    dateAdded: "2024-01-20",
  },
  {
    id: 57,
    title: "Gold Party Cups Set",
    description: "Elegant gold party cups perfect for celebrations, parties, and special occasions.",
    price: "$12.00",
    image: "/images/gold-party-cups.jpg",
    alt: "Elegant gold party cups for celebrations",
    rating: 4.4,
    reviews: 68,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "gifts",
    features: [
      "Metallic gold finish",
      "Disposable convenience",
      "Elegant party design",
      "Multiple cups per pack",
      "Sturdy construction",
    ],
    benefits: [
      "Adds elegance to parties",
      "Easy cleanup",
      "Perfect for celebrations",
      "Great value pack",
      "Impressive presentation",
    ],
    category: "Party Supplies",
    dateAdded: "2024-01-19",
  },
  {
    id: 58,
    title: "Birthday Gift Boxes Stack",
    description: "Beautiful stack of decorative birthday gift boxes in various sizes, perfect for gift presentation.",
    price: "$25.00",
    image: "/images/birthday-gift-boxes-stack.jpg",
    alt: "Stack of decorative birthday gift boxes in various sizes",
    rating: 4.7,
    reviews: 29,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "gifts",
    features: [
      "Multiple box sizes",
      "Festive birthday designs",
      "Stackable design",
      "Reusable boxes",
      "Colorful patterns",
    ],
    benefits: [
      "Perfect gift presentation",
      "Multiple uses",
      "Creates excitement",
      "Eco-friendly reusable",
      "Great for organizing",
    ],
    category: "Gift Boxes",
    dateAdded: "2024-01-18",
  },
  {
    id: 59,
    title: "Best Wishes Gift Bag",
    description: "Elegant 'Best Wishes' gift bag perfect for special occasions and thoughtful gift giving.",
    price: "$6.00",
    image: "/images/best-wishes-gift-bag.jpg",
    alt: "Elegant Best Wishes gift bag for special occasions",
    rating: 4.3,
    reviews: 47,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "gifts",
    features: [
      "Best Wishes message",
      "Premium quality material",
      "Elegant design",
      "Sturdy handles",
      "Perfect gift size",
    ],
    benefits: [
      "Perfect for any occasion",
      "Professional presentation",
      "Reusable quality",
      "Thoughtful message",
      "Easy gift wrapping",
    ],
    category: "Gift Bags",
    dateAdded: "2024-01-17",
  },

  // Sports and Outdoor (40-49)
  {
    id: 40,
    title: "Blue & White Soccer Ball",
    description:
      "Classic blue and white soccer ball perfect for outdoor play, sports activities, and developing athletic skills.",
    price: "$15.00",
    image: "/images/blue-white-soccer-ball.jpg",
    alt: "Classic blue and white soccer ball for outdoor play",
    rating: 4.5,
    reviews: 83,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Official size and weight",
      "Durable synthetic leather",
      "Blue and white design",
      "Perfect bounce",
      "Weather resistant",
    ],
    benefits: [
      "Encourages physical activity",
      "Develops coordination",
      "Suitable for all ages",
      "Long-lasting durability",
      "Perfect for team sports",
    ],
    category: "Sports Equipment",
    dateAdded: "2024-01-16",
  },
  {
    id: 41,
    title: "Green Leafy Houseplant",
    description:
      "Beautiful green leafy houseplant perfect for indoor decoration and improving air quality in your home.",
    price: "$28.00",
    image: "/images/green-leafy-houseplant.jpg",
    alt: "Beautiful green leafy houseplant for indoor decoration",
    rating: 4.6,
    reviews: 34,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "home-decor",
    features: [
      "Air purifying qualities",
      "Low maintenance care",
      "Lush green foliage",
      "Decorative pot included",
      "Indoor plant variety",
    ],
    benefits: [
      "Improves indoor air quality",
      "Adds natural beauty",
      "Easy to care for",
      "Reduces stress",
      "Perfect home accent",
    ],
    category: "Plants",
    dateAdded: "2024-01-15",
  },
  {
    id: 42,
    title: "Decorative Flower Planter Box",
    description: "Elegant decorative flower planter box with beautiful blooms, perfect for home and garden decoration.",
    price: "$40.00",
    image: "/images/decorative-flower-planter-box.jpg",
    alt: "Elegant decorative flower planter box with beautiful blooms",
    rating: 4.7,
    reviews: 26,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "home-decor",
    features: [
      "Wooden planter box",
      "Artificial flowers included",
      "Weather resistant finish",
      "Multiple flower varieties",
      "Ready to display",
    ],
    benefits: [
      "No maintenance required",
      "Long-lasting beauty",
      "Perfect for any season",
      "Adds charm to spaces",
      "Great housewarming gift",
    ],
    category: "Garden Decor",
    dateAdded: "2024-01-14",
  },
  {
    id: 43,
    title: "Miniature Fairy Garden Setup",
    description:
      "Enchanting miniature fairy garden setup complete with tiny accessories and magical details for imaginative play.",
    price: "$55.00",
    image: "/images/miniature-fairy-garden-setup.jpg",
    alt: "Enchanting miniature fairy garden setup with tiny accessories",
    rating: 4.9,
    reviews: 18,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Complete fairy garden kit",
      "Miniature accessories",
      "Magical themed pieces",
      "Detailed craftsmanship",
      "Expandable collection",
    ],
    benefits: [
      "Encourages imagination",
      "Develops creativity",
      "Perfect for storytelling",
      "Educational play value",
      "Collectible items",
    ],
    category: "Imaginative Play",
    dateAdded: "2024-01-13",
  },
  {
    id: 44,
    title: "Miniature Garden Detailed View",
    description:
      "Detailed miniature garden with intricate landscaping and tiny decorative elements for collectors and enthusiasts.",
    price: "$48.00",
    image: "/images/miniature-garden-detailed-view.jpg",
    alt: "Detailed miniature garden with intricate landscaping",
    rating: 4.8,
    reviews: 22,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "home-decor",
    features: [
      "Intricate detail work",
      "Miniature landscaping",
      "Collector quality",
      "Handcrafted elements",
      "Display ready",
    ],
    benefits: [
      "Perfect conversation piece",
      "Collector's item",
      "Stress-relieving hobby",
      "Unique home decor",
      "Artistic appreciation",
    ],
    category: "Collectibles",
    dateAdded: "2024-01-12",
  },
  {
    id: 45,
    title: "Yellow Off-Road Toy Truck",
    description: "Rugged yellow off-road toy truck perfect for outdoor adventures and imaginative construction play.",
    price: "$22.00",
    image: "/images/yellow-off-road-toy-truck.jpg",
    alt: "Rugged yellow off-road toy truck for outdoor play",
    rating: 4.6,
    reviews: 45,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Durable construction", "Off-road design", "Bright yellow color", "Moving parts", "Safe materials"],
    benefits: [
      "Encourages outdoor play",
      "Develops motor skills",
      "Stimulates imagination",
      "Durable for rough play",
      "Perfect for sandbox",
    ],
    category: "Toy Vehicles",
    dateAdded: "2024-01-11",
  },
  {
    id: 46,
    title: "Home Planter with Orange Flowers",
    description:
      "Beautiful home planter featuring vibrant orange flowers, perfect for brightening any indoor or outdoor space.",
    price: "$35.00",
    image: "/images/home-planter-orange-flowers.jpg",
    alt: "Home planter with vibrant orange flowers",
    rating: 4.5,
    reviews: 31,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "home-decor",
    features: [
      "Vibrant orange blooms",
      "Decorative planter",
      "Low maintenance",
      "Indoor/outdoor use",
      "Long-lasting flowers",
    ],
    benefits: [
      "Brightens living spaces",
      "Easy to maintain",
      "Versatile placement",
      "Adds color and life",
      "Perfect home accent",
    ],
    category: "Planters",
    dateAdded: "2024-01-10",
  },
  {
    id: 47,
    title: "Blue Home Planter with Red Roses",
    description:
      "Elegant blue planter featuring beautiful red roses, creating a stunning contrast for home decoration.",
    price: "$38.00",
    image: "/images/blue-home-planter-red-roses.jpg",
    alt: "Blue planter with beautiful red roses",
    rating: 4.7,
    reviews: 28,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "home-decor",
    features: [
      "Blue decorative planter",
      "Red rose blooms",
      "Color contrast design",
      "Premium quality",
      "Ready to display",
    ],
    benefits: [
      "Creates visual impact",
      "Elegant home decor",
      "No maintenance needed",
      "Perfect color combination",
      "Instant room enhancement",
    ],
    category: "Planters",
    dateAdded: "2024-01-09",
  },
  {
    id: 48,
    title: "Light-Up Balloons Package",
    description:
      "Magical light-up balloons package perfect for parties, celebrations, and creating enchanting atmospheres.",
    price: "$18.00",
    image: "/images/light-up-balloons-package.jpg",
    alt: "Magical light-up balloons package for parties",
    rating: 4.4,
    reviews: 62,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "gifts",
    features: [
      "LED light technology",
      "Multiple balloons included",
      "Battery operated",
      "Various colors",
      "Party decoration",
    ],
    benefits: [
      "Creates magical atmosphere",
      "Perfect for night parties",
      "Safe LED lighting",
      "Reusable entertainment",
      "Memorable celebrations",
    ],
    category: "Party Supplies",
    dateAdded: "2024-01-08",
  },
  {
    id: 49,
    title: "Decorative Crown Wands",
    description:
      "Beautiful decorative crown wands perfect for dress-up play, parties, and princess-themed celebrations.",
    price: "$14.00",
    image: "/images/decorative-crown-wands.jpg",
    alt: "Beautiful decorative crown wands for dress-up play",
    rating: 4.6,
    reviews: 37,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Crown and wand set",
      "Sparkly decorations",
      "Safe plastic construction",
      "Princess theme",
      "Party accessories",
    ],
    benefits: [
      "Encourages imaginative play",
      "Perfect for dress-up",
      "Great party favors",
      "Develops creativity",
      "Hours of entertainment",
    ],
    category: "Dress-up",
    dateAdded: "2024-01-07",
  },

  // Toys and Action Figures (30-39)
  {
    id: 30,
    title: "Tactical Toy Rifle - Black",
    description:
      "Realistic tactical toy rifle in black, perfect for role-playing games and outdoor adventure activities.",
    price: "$35.00",
    image: "/images/tactical-toy-rifle-black.jpg",
    alt: "Realistic tactical toy rifle in black for role-playing",
    rating: 4.3,
    reviews: 56,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Realistic design",
      "Safe toy construction",
      "Black tactical finish",
      "Lightweight materials",
      "Age-appropriate",
    ],
    benefits: [
      "Encourages active play",
      "Develops coordination",
      "Safe for children",
      "Durable construction",
      "Perfect for outdoor games",
    ],
    category: "Action Toys",
    dateAdded: "2024-01-06",
  },
  {
    id: 31,
    title: "Chimi Doll Collection Edition",
    description:
      "Special edition Chimi doll from the collectible series, featuring unique design and premium quality craftsmanship.",
    price: "$28.00",
    image: "/images/chimi-doll-collection-edition.jpg",
    alt: "Special edition Chimi doll with unique design",
    rating: 4.7,
    reviews: 34,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Collectible edition",
      "Premium quality materials",
      "Unique character design",
      "Detailed craftsmanship",
      "Limited series",
    ],
    benefits: [
      "Collector's value",
      "High-quality construction",
      "Unique character",
      "Perfect for gifting",
      "Encourages collecting hobby",
    ],
    category: "Collectible Dolls",
    dateAdded: "2024-01-05",
  },
  {
    id: 32,
    title: "U8 War Police Robot",
    description: "Advanced U8 war police robot toy with interactive features and realistic police-themed design.",
    price: "$45.00",
    image: "/images/u8-war-police-robot.jpg",
    alt: "Advanced U8 war police robot with interactive features",
    rating: 4.8,
    reviews: 29,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Interactive robot features",
      "Police theme design",
      "Sound and light effects",
      "Durable construction",
      "Battery operated",
    ],
    benefits: [
      "Educational STEM play",
      "Develops problem-solving",
      "Interactive entertainment",
      "Encourages imagination",
      "High-tech play experience",
    ],
    category: "Robot Toys",
    dateAdded: "2024-01-04",
  },
  {
    id: 33,
    title: "Musical Cactus Toy - Green",
    description:
      "Adorable green musical cactus toy that dances and plays music, perfect for entertainment and learning.",
    price: "$25.00",
    image: "/images/musical-cactus-toy-green.jpg",
    alt: "Adorable green musical cactus toy that dances",
    rating: 4.6,
    reviews: 78,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Musical and dancing features",
      "Cute cactus design",
      "Interactive play",
      "Educational songs",
      "Battery operated",
    ],
    benefits: [
      "Develops musical appreciation",
      "Encourages movement",
      "Educational entertainment",
      "Adorable companion",
      "Stimulates sensory development",
    ],
    category: "Musical Toys",
    dateAdded: "2024-01-03",
  },
  {
    id: 34,
    title: "Colorful Confetti Poppers Set",
    description: "Fun colorful confetti poppers set perfect for celebrations, parties, and special occasions.",
    price: "$12.00",
    image: "/images/colorful-confetti-poppers-set.jpg",
    alt: "Fun colorful confetti poppers set for celebrations",
    rating: 4.2,
    reviews: 95,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "gifts",
    features: [
      "Multiple poppers included",
      "Colorful confetti",
      "Safe party supplies",
      "Easy to use",
      "Celebration essentials",
    ],
    benefits: [
      "Creates festive atmosphere",
      "Perfect for celebrations",
      "Safe for all ages",
      "Memorable moments",
      "Great party addition",
    ],
    category: "Party Supplies",
    dateAdded: "2024-01-02",
  },
  {
    id: 35,
    title: "Pink Roses in Decorative Pot",
    description: "Beautiful pink roses arranged in an elegant decorative pot, perfect for home decoration and gifting.",
    price: "$30.00",
    image: "/images/pink-roses-decorative-pot.jpg",
    alt: "Beautiful pink roses in elegant decorative pot",
    rating: 4.8,
    reviews: 41,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "home-decor",
    features: [
      "Artificial pink roses",
      "Decorative pot included",
      "Long-lasting beauty",
      "No maintenance required",
      "Elegant arrangement",
    ],
    benefits: [
      "Permanent floral beauty",
      "No watering needed",
      "Perfect home accent",
      "Great gift option",
      "Allergy-friendly",
    ],
    category: "Artificial Flowers",
    dateAdded: "2024-01-01",
  },
  {
    id: 36,
    title: "Purple Flowers in Wooden Pot",
    description: "Charming purple flowers beautifully arranged in a rustic wooden pot for natural home decoration.",
    price: "$32.00",
    image: "/images/purple-flowers-wooden-pot.jpg",
    alt: "Charming purple flowers in rustic wooden pot",
    rating: 4.5,
    reviews: 33,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "home-decor",
    features: [
      "Purple flower arrangement",
      "Rustic wooden pot",
      "Natural home decor",
      "Artificial flowers",
      "Maintenance-free",
    ],
    benefits: [
      "Adds natural charm",
      "No care required",
      "Rustic aesthetic appeal",
      "Perfect for any room",
      "Long-lasting decoration",
    ],
    category: "Artificial Flowers",
    dateAdded: "2023-12-31",
  },
  {
    id: 37,
    title: "Pink Dahlias in Woven Basket",
    description:
      "Stunning pink dahlias beautifully arranged in a handwoven basket, perfect for elegant home decoration.",
    price: "$35.00",
    image: "/images/pink-dahlias-woven-basket.jpg",
    alt: "Stunning pink dahlias in handwoven basket",
    rating: 4.9,
    reviews: 27,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "home-decor",
    features: ["Pink dahlia flowers", "Handwoven basket", "Elegant arrangement", "Premium quality", "Ready to display"],
    benefits: [
      "Elegant home accent",
      "Handcrafted quality",
      "Perfect centerpiece",
      "No maintenance needed",
      "Sophisticated decoration",
    ],
    category: "Artificial Flowers",
    dateAdded: "2023-12-30",
  },
  {
    id: 38,
    title: "Mixed Roses in Woven Basket",
    description: "Beautiful mixed roses arrangement in a charming woven basket, perfect for any home decoration style.",
    price: "$38.00",
    image: "/images/mixed-roses-woven-basket.jpg",
    alt: "Beautiful mixed roses in charming woven basket",
    rating: 4.7,
    reviews: 39,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "home-decor",
    features: [
      "Mixed rose varieties",
      "Woven basket container",
      "Diverse color palette",
      "Professional arrangement",
      "Home decor ready",
    ],
    benefits: [
      "Versatile color scheme",
      "Professional quality",
      "Perfect for any decor",
      "Long-lasting beauty",
      "Great gift choice",
    ],
    category: "Artificial Flowers",
    dateAdded: "2023-12-29",
  },
  {
    id: 39,
    title: "Pink Roses in Wire Hoop Basket",
    description:
      "Elegant pink roses arranged in a modern wire hoop basket, combining contemporary style with classic beauty.",
    price: "$33.00",
    image: "/images/pink-roses-wire-hoop-basket.jpg",
    alt: "Elegant pink roses in modern wire hoop basket",
    rating: 4.6,
    reviews: 44,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "home-decor",
    features: [
      "Pink rose arrangement",
      "Modern wire hoop design",
      "Contemporary style",
      "Artificial flowers",
      "Stylish presentation",
    ],
    benefits: [
      "Modern aesthetic appeal",
      "Perfect for contemporary homes",
      "No maintenance required",
      "Stylish decoration",
      "Unique design element",
    ],
    category: "Artificial Flowers",
    dateAdded: "2023-12-28",
  },

  // More Toys and Educational Items (20-29)
  {
    id: 20,
    title: "Lunabebe Medical Play Set",
    description:
      "Educational medical play set that encourages role-playing and helps children learn about healthcare in a fun way.",
    price: "$32.00",
    image: "/images/lunabebe-medical-play-set.jpg",
    alt: "Educational medical play set for children",
    rating: 4.7,
    reviews: 52,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Complete medical kit",
      "Educational play",
      "Safe plastic materials",
      "Role-playing accessories",
      "Realistic medical tools",
    ],
    benefits: [
      "Encourages empathy",
      "Educational value",
      "Reduces medical anxiety",
      "Develops social skills",
      "Safe imaginative play",
    ],
    category: "Educational Toys",
    dateAdded: "2023-12-27",
  },
  {
    id: 21,
    title: "Peek-a-Boos Phone Holder",
    description:
      "Cute and functional phone holder with adorable character design, perfect for hands-free viewing and decoration.",
    price: "$15.00",
    image: "/images/peek-a-boos-phone-holder.jpg",
    alt: "Cute character phone holder for hands-free viewing",
    rating: 4.4,
    reviews: 67,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "gifts",
    features: [
      "Adorable character design",
      "Universal phone compatibility",
      "Stable base",
      "Adjustable viewing angles",
      "Compact size",
    ],
    benefits: [
      "Hands-free convenience",
      "Cute desk accessory",
      "Perfect for video calls",
      "Great gift item",
      "Functional decoration",
    ],
    category: "Phone Accessories",
    dateAdded: "2023-12-26",
  },
  {
    id: 22,
    title: "Lion Plush Toy - Brown",
    description: "Soft and cuddly brown lion plush toy, perfect for snuggling and imaginative play adventures.",
    price: "$18.00",
    image: "/images/lion-plush-toy-brown.jpg",
    alt: "Soft brown lion plush toy for cuddling",
    rating: 4.8,
    reviews: 89,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Ultra-soft plush material",
      "Realistic lion design",
      "Perfect cuddling size",
      "Machine washable",
      "Child-safe construction",
    ],
    benefits: [
      "Provides comfort",
      "Encourages imaginative play",
      "Perfect bedtime companion",
      "Develops nurturing skills",
      "Long-lasting quality",
    ],
    category: "Plush Toys",
    dateAdded: "2023-12-25",
  },
  {
    id: 23,
    title: "Colorful Pony Toys Set",
    description:
      "Vibrant set of colorful pony toys with brushable manes and accessories for creative play and styling fun.",
    price: "$24.00",
    image: "/images/colorful-pony-toys-set.jpg",
    alt: "Vibrant set of colorful pony toys with accessories",
    rating: 4.6,
    reviews: 73,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Multiple colorful ponies",
      "Brushable manes",
      "Styling accessories",
      "Collectible figures",
      "Creative play elements",
    ],
    benefits: [
      "Encourages creativity",
      "Develops fine motor skills",
      "Collectible fun",
      "Social play opportunities",
      "Imaginative storytelling",
    ],
    category: "Collectible Toys",
    dateAdded: "2023-12-24",
  },
  {
    id: 24,
    title: "Wet Brush Mini Detangler",
    description: "Professional mini detangling brush designed to gently remove knots and tangles from wet or dry hair.",
    price: "$12.00",
    image: "/images/wet-brush-mini-detangler.jpg",
    alt: "Professional mini detangling brush for hair care",
    rating: 4.9,
    reviews: 156,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "skincare",
    features: [
      "Professional quality",
      "Gentle detangling",
      "Wet and dry use",
      "Compact travel size",
      "Ergonomic handle",
    ],
    benefits: [
      "Reduces hair breakage",
      "Pain-free detangling",
      "Perfect for travel",
      "Suitable for all hair types",
      "Professional results",
    ],
    category: "Hair Care",
    dateAdded: "2023-12-23",
  },
  {
    id: 25,
    title: "Fire Truck & Helicopter Set",
    description:
      "Exciting emergency vehicle set featuring detailed fire truck and rescue helicopter for action-packed play.",
    price: "$28.00",
    image: "/images/fire-truck-helicopter-set.jpg",
    alt: "Emergency vehicle set with fire truck and helicopter",
    rating: 4.7,
    reviews: 64,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Detailed emergency vehicles",
      "Moving parts",
      "Realistic designs",
      "Durable construction",
      "Educational play value",
    ],
    benefits: [
      "Teaches about emergency services",
      "Encourages heroic play",
      "Develops motor skills",
      "Social play opportunities",
      "Long-lasting entertainment",
    ],
    category: "Vehicle Toys",
    dateAdded: "2023-12-22",
  },
  {
    id: 26,
    title: "Top Speed Sports Cars",
    description:
      "Collection of high-speed sports car models with sleek designs and racing-inspired details for car enthusiasts.",
    price: "$22.00",
    image: "/images/top-speed-sports-cars.jpg",
    alt: "Collection of high-speed sports car models",
    rating: 4.5,
    reviews: 81,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Multiple sports car models",
      "Realistic details",
      "High-quality construction",
      "Racing-inspired designs",
      "Collectible series",
    ],
    benefits: [
      "Perfect for car enthusiasts",
      "Collectible value",
      "Encourages interest in automobiles",
      "Display-worthy quality",
      "Great gift for boys",
    ],
    category: "Die-cast Cars",
    dateAdded: "2023-12-21",
  },
  {
    id: 27,
    title: "Accessories Variety Pack",
    description:
      "Diverse collection of fun accessories and small toys perfect for party favors, gifts, and everyday play.",
    price: "$16.00",
    image: "/images/accessories-variety-pack.jpg",
    alt: "Diverse collection of fun accessories and small toys",
    rating: 4.3,
    reviews: 92,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "gifts",
    features: [
      "Multiple accessories included",
      "Variety of items",
      "Perfect for sharing",
      "Colorful designs",
      "Great value pack",
    ],
    benefits: [
      "Perfect for party favors",
      "Great value for money",
      "Encourages sharing",
      "Variety keeps interest",
      "Suitable for all ages",
    ],
    category: "Variety Packs",
    dateAdded: "2023-12-20",
  },
  {
    id: 28,
    title: "Blue Sports Car Model",
    description:
      "Detailed blue sports car model with authentic styling and premium finish, perfect for collectors and car lovers.",
    price: "$19.00",
    image: "/images/blue-sports-car-model.jpg",
    alt: "Detailed blue sports car model with premium finish",
    rating: 4.6,
    reviews: 47,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Authentic styling", "Premium finish", "Detailed craftsmanship", "Collector quality", "Display-ready"],
    benefits: [
      "Perfect for collectors",
      "High-quality construction",
      "Great display piece",
      "Educational about cars",
      "Lasting value",
    ],
    category: "Model Cars",
    dateAdded: "2023-12-19",
  },
  {
    id: 29,
    title: "Kids Melody Projection Light",
    description:
      "Magical projection light that plays soothing melodies and creates beautiful light patterns for bedtime comfort.",
    price: "$26.00",
    image: "/images/kids-melody-projection-light.jpg",
    alt: "Magical projection light with melodies for bedtime",
    rating: 4.8,
    reviews: 68,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Soothing melodies",
      "Beautiful light projections",
      "Multiple patterns",
      "Timer function",
      "Portable design",
    ],
    benefits: [
      "Helps with bedtime routine",
      "Creates calming atmosphere",
      "Reduces bedtime anxiety",
      "Educational light patterns",
      "Perfect night light",
    ],
    category: "Night Lights",
    dateAdded: "2023-12-18",
  },

  // Party and Celebration Items (10-19)
  {
    id: 10,
    title: "Happy Letter Candles",
    description: "Colorful letter candles spelling 'HAPPY' perfect for birthday celebrations and special occasions.",
    price: "$8.00",
    image: "/images/happy-letter-candles.jpg",
    alt: "Colorful letter candles spelling HAPPY for celebrations",
    rating: 4.4,
    reviews: 125,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "gifts",
    features: ["Spells 'HAPPY'", "Colorful design", "Birthday candles", "Easy to light", "Celebration essential"],
    benefits: [
      "Perfect for birthdays",
      "Creates festive mood",
      "Great photo opportunities",
      "Memorable celebrations",
      "Easy to use",
    ],
    category: "Birthday Candles",
    dateAdded: "2023-12-17",
  },
  {
    id: 11,
    title: "Rainbow Spiral Candles",
    description:
      "Beautiful rainbow-colored spiral candles that add a magical touch to any birthday cake or celebration.",
    price: "$6.00",
    image: "/images/rainbow-spiral-candles.jpg",
    alt: "Beautiful rainbow spiral candles for birthday cakes",
    rating: 4.6,
    reviews: 98,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "gifts",
    features: [
      "Rainbow colors",
      "Spiral design",
      "Birthday cake candles",
      "Magical appearance",
      "Set of multiple candles",
    ],
    benefits: [
      "Adds magic to celebrations",
      "Beautiful rainbow effect",
      "Perfect for photos",
      "Creates wonder",
      "Great value pack",
    ],
    category: "Birthday Candles",
    dateAdded: "2023-12-16",
  },
  {
    id: 12,
    title: "Gold Number 9 Candle",
    description: "Elegant gold number 9 candle perfect for 9th birthday celebrations and milestone moments.",
    price: "$4.00",
    image: "/images/gold-number-9-candle.jpg",
    alt: "Elegant gold number 9 candle for birthday celebrations",
    rating: 4.5,
    reviews: 76,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "gifts",
    features: [
      "Gold metallic finish",
      "Number 9 design",
      "Premium quality",
      "Birthday milestone",
      "Elegant appearance",
    ],
    benefits: [
      "Perfect for 9th birthday",
      "Elegant gold finish",
      "Memorable milestone",
      "Great for photos",
      "Premium quality",
    ],
    category: "Number Candles",
    dateAdded: "2023-12-15",
  },
  {
    id: 13,
    title: "Travel Bassinet for Baby",
    description: "Portable travel bassinet designed for safe and comfortable baby sleep during trips and outings.",
    price: "$65.00",
    image: "/images/travel-bassinet-baby.jpg",
    alt: "Portable travel bassinet for safe baby sleep",
    rating: 4.9,
    reviews: 43,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Portable design", "Safe sleep environment", "Easy setup", "Compact when folded", "Travel-friendly"],
    benefits: [
      "Safe sleep anywhere",
      "Perfect for travel",
      "Easy to transport",
      "Gives parents peace of mind",
      "Comfortable for baby",
    ],
    category: "Baby Travel",
    dateAdded: "2023-12-14",
  },
  {
    id: 14,
    title: "Blue Astronaut Kids Suitcase",
    description: "Fun blue astronaut-themed kids suitcase perfect for travel adventures and encouraging independence.",
    price: "$42.00",
    image: "/images/blue-astronaut-kids-suitcase.jpg",
    alt: "Fun blue astronaut-themed kids suitcase for travel",
    rating: 4.7,
    reviews: 58,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Astronaut theme", "Kid-friendly size", "Durable construction", "Rolling wheels", "Fun space design"],
    benefits: [
      "Encourages independence",
      "Makes travel fun",
      "Perfect size for kids",
      "Durable for travel",
      "Inspiring space theme",
    ],
    category: "Kids Luggage",
    dateAdded: "2023-12-13",
  },
  {
    id: 15,
    title: "Mint Dinosaur Kids Suitcase",
    description:
      "Adorable mint green dinosaur-themed kids suitcase that makes traveling an exciting adventure for little ones.",
    price: "$42.00",
    image: "/images/mint-dinosaur-kids-suitcase.jpg",
    alt: "Mint green dinosaur-themed kids suitcase for adventures",
    rating: 4.8,
    reviews: 51,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Dinosaur theme", "Mint green color", "Child-sized", "Sturdy wheels", "Fun prehistoric design"],
    benefits: [
      "Makes travel exciting",
      "Perfect for dinosaur lovers",
      "Encourages packing skills",
      "Durable construction",
      "Great for overnight trips",
    ],
    category: "Kids Luggage",
    dateAdded: "2023-12-12",
  },
  {
    id: 16,
    title: "Pink Astronaut Kids Suitcase",
    description:
      "Charming pink astronaut-themed kids suitcase designed to inspire dreams of space exploration and adventure.",
    price: "$42.00",
    image: "/images/pink-astronaut-kids-suitcase.jpg",
    alt: "Charming pink astronaut-themed kids suitcase",
    rating: 4.6,
    reviews: 44,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Pink astronaut theme",
      "Space-inspired design",
      "Perfect for girls",
      "Rolling functionality",
      "Lightweight construction",
    ],
    benefits: [
      "Inspires space dreams",
      "Perfect for young girls",
      "Easy to maneuver",
      "Encourages travel",
      "Beautiful pink design",
    ],
    category: "Kids Luggage",
    dateAdded: "2023-12-11",
  },
  {
    id: 17,
    title: "Spiderman Action Figure",
    description:
      "Dynamic Spiderman action figure with articulated joints and authentic costume details for superhero adventures.",
    price: "$16.00",
    image: "/images/spiderman-action-figure.jpg",
    alt: "Dynamic Spiderman action figure with authentic details",
    rating: 4.8,
    reviews: 134,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Articulated joints", "Authentic costume", "Superhero figure", "Durable construction", "Action poses"],
    benefits: [
      "Encourages heroic play",
      "Develops imagination",
      "Perfect for superhero fans",
      "Great collectible",
      "Inspires bravery",
    ],
    category: "Action Figures",
    dateAdded: "2023-12-10",
  },
  {
    id: 18,
    title: "Off-Road RC Trucks",
    description: "Powerful remote-controlled off-road trucks built for outdoor adventures and all-terrain exploration.",
    price: "$55.00",
    image: "/images/off-road-rc-trucks.jpg",
    alt: "Powerful remote-controlled off-road trucks for adventures",
    rating: 4.7,
    reviews: 67,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Remote controlled",
      "Off-road capability",
      "Durable construction",
      "All-terrain tires",
      "Rechargeable battery",
    ],
    benefits: [
      "Outdoor adventure fun",
      "Develops hand-eye coordination",
      "Great for all terrains",
      "Long-lasting entertainment",
      "Perfect for outdoor play",
    ],
    category: "RC Vehicles",
    dateAdded: "2023-12-09",
  },
  {
    id: 19,
    title: "RC Snake Toy",
    description:
      "Realistic remote-controlled snake toy that slithers and moves like a real snake for thrilling play experiences.",
    price: "$24.00",
    image: "/images/rc-snake-toy.jpg",
    alt: "Realistic remote-controlled snake toy for thrilling play",
    rating: 4.4,
    reviews: 89,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Realistic movement", "Remote controlled", "Slithering action", "Surprise element", "Battery operated"],
    benefits: [
      "Thrilling play experience",
      "Great for pranks",
      "Realistic movement",
      "Develops motor skills",
      "Unique toy concept",
    ],
    category: "RC Toys",
    dateAdded: "2023-12-08",
  },

  // Featured skincare products (1-9)
  {
    id: 1001,
    title: "F&W Mix Ready 2 Glow Kit",
    description:
      "Complete body brightening system featuring concentrated serum and body lotion for radiant, glowing skin. This premium French-made kit combines advanced skincare technology with natural ingredients to deliver visible results.",
    price: "$28.50",
    originalPrice: "$32.00",
    image: "/images/fw-mix-glow-kit.jpg",
    alt: "F&W Paris Mix Ready 2 Glow body brightening kit with concentrated serum and body lotion",
    rating: 4.8,
    reviews: 124,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "skincare",
    features: ["Body Brightening", "Made in France", "2-in-1 Kit", "Premium Quality", "Concentrated Serum"],
    benefits: ["Evens skin tone", "Reduces dark spots", "Hydrates deeply", "Long-lasting results"],
    category: "Body Care",
    dateAdded: "2024-01-15",
  },
  {
    id: 1002,
    title: "CeraVe Acne Foaming Cleanser",
    description:
      "Dermatologist-developed foaming cream cleanser with 4% Benzoyl Peroxide for effective acne treatment. Gentle yet powerful formula suitable for daily use on acne-prone skin.",
    price: "$16.50",
    originalPrice: "$18.50",
    image: "/images/cerave-acne-cleanser.jpg",
    alt: "CeraVe Acne Foaming Cream Cleanser with 4% Benzoyl Peroxide for acne treatment",
    rating: 4.6,
    reviews: 89,
    inStock: true,
    isPopular: false,
    isNew: true,
    categoryId: "skincare",
    features: ["4% Benzoyl Peroxide", "Dermatologist Developed", "Daily Use", "Acne Treatment", "Gentle Formula"],
    benefits: ["Clears acne", "Prevents breakouts", "Gentle on skin", "Clinically tested"],
    category: "Facial Care",
    dateAdded: "2024-02-01",
  },
  {
    id: 1003,
    title: "Queen Helene Mint Julep Set",
    description:
      "Refreshing mint julep scrub and masque duo for deep pore cleansing. Perfect for oily and acne-prone skin with natural mint extracts that provide a cooling, refreshing sensation.",
    price: "$9.50",
    originalPrice: "$11.00",
    image: "/images/mint-julep-skincare.jpg",
    alt: "Queen Helene Mint Julep Scrub and Masque skincare set for oily and acne-prone skin",
    rating: 4.4,
    reviews: 67,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "skincare",
    features: ["Deep Cleansing", "Natural Mint", "Scrub & Masque", "Oily Skin", "Cooling Effect"],
    benefits: ["Deep pore cleansing", "Controls oil", "Refreshes skin", "Natural ingredients"],
    category: "Facial Treatment",
    dateAdded: "2024-01-10",
  },
  {
    id: 1004,
    title: "Hero Cosmetics Premium Collection",
    description:
      "Complete Hero Cosmetics premium collection featuring targeted treatments for clear, healthy-looking skin with clinically tested ingredients.",
    price: "$24.99",
    originalPrice: "$29.99",
    image: "/images/hero-cosmetics-premium.jpg",
    alt: "Hero Cosmetics Premium skincare collection with targeted treatments",
    rating: 4.7,
    reviews: 156,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "skincare",
    features: [
      "Targeted Treatments",
      "Clinically Tested",
      "Premium Quality",
      "Complete System",
      "Dermatologist Approved",
    ],
    benefits: ["Clear skin", "Reduces blemishes", "Professional results", "Gentle formula"],
    category: "Skincare System",
    dateAdded: "2024-01-20",
  },
  {
    id: 1005,
    title: "Plush Doll Carrier Bag",
    description: "Adorable plush doll carrier bag perfect for carrying favorite dolls and toys on adventures.",
    price: "$18.00",
    image: "/images/plush-doll-carrier-bag.jpg",
    alt: "Adorable plush doll carrier bag for toys",
    rating: 4.5,
    reviews: 73,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Soft plush material",
      "Doll carrier design",
      "Comfortable handles",
      "Secure closure",
      "Cute character design",
    ],
    benefits: [
      "Perfect for imaginative play",
      "Encourages nurturing behavior",
      "Easy to carry",
      "Develops responsibility",
      "Great travel companion",
    ],
    category: "Doll Accessories",
    dateAdded: "2024-01-05",
  },
  {
    id: 1006,
    title: "Dreamcatcher Diaper Bag",
    description:
      "Stylish dreamcatcher-themed diaper bag with multiple compartments for organized baby care essentials.",
    price: "$45.00",
    image: "/images/dreamcatcher-diaper-bag.jpg",
    alt: "Stylish dreamcatcher-themed diaper bag with compartments",
    rating: 4.8,
    reviews: 92,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Multiple compartments",
      "Dreamcatcher design",
      "Waterproof lining",
      "Adjustable straps",
      "Large capacity",
    ],
    benefits: [
      "Keeps baby items organized",
      "Stylish and functional",
      "Easy to clean",
      "Comfortable to carry",
      "Perfect for new parents",
    ],
    category: "Baby Bags",
    dateAdded: "2024-01-03",
  },
  {
    id: 1007,
    title: "Baby Clothing Gift Set - Safari",
    description: "Adorable safari-themed baby clothing gift set with multiple pieces featuring cute animal prints.",
    price: "$32.00",
    image: "/images/baby-clothing-gift-set-1.jpg",
    alt: "Safari-themed baby clothing gift set with animal prints",
    rating: 4.9,
    reviews: 108,
    inStock: true,
    isPopular: true,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Safari animal theme",
      "Multiple clothing pieces",
      "Soft cotton material",
      "Gift-ready packaging",
      "Various sizes available",
    ],
    benefits: [
      "Complete outfit solution",
      "Gentle on baby's skin",
      "Perfect gift choice",
      "Adorable animal designs",
      "Great value set",
    ],
    category: "Baby Clothing Sets",
    dateAdded: "2024-01-02",
  },
  {
    id: 1008,
    title: "Baby Clothing Gift Set - Ocean",
    description:
      "Charming ocean-themed baby clothing gift set with sea creature designs and soft, comfortable fabrics.",
    price: "$32.00",
    image: "/images/baby-clothing-gift-set-2.jpg",
    alt: "Ocean-themed baby clothing gift set with sea creatures",
    rating: 4.7,
    reviews: 85,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: ["Ocean theme design", "Sea creature prints", "Comfortable fit", "Easy care fabric", "Complete set"],
    benefits: [
      "Stimulates visual development",
      "Comfortable for all-day wear",
      "Easy for parents to maintain",
      "Educational sea themes",
      "Perfect baby shower gift",
    ],
    category: "Baby Clothing Sets",
    dateAdded: "2024-01-01",
  },
  {
    id: 1009,
    title: "Baby Clothing Gift Set - Garden",
    description:
      "Beautiful garden-themed baby clothing gift set featuring floral patterns and nature-inspired designs.",
    price: "$32.00",
    image: "/images/baby-clothing-gift-set-3.jpg",
    alt: "Garden-themed baby clothing gift set with floral patterns",
    rating: 4.8,
    reviews: 96,
    inStock: true,
    isPopular: false,
    isNew: false,
    categoryId: "kids-gifts",
    features: [
      "Garden floral theme",
      "Nature-inspired patterns",
      "Premium cotton blend",
      "Snap closures",
      "Machine washable",
    ],
    benefits: [
      "Connects baby with nature",
      "Easy diaper changes",
      "Long-lasting quality",
      "Beautiful gift presentation",
      "Suitable for any season",
    ],
    category: "Baby Clothing Sets",
    dateAdded: "2023-12-31",
  },
]

// Initialize products with robust error handling and data persistence
export function initializeProducts(): Product[] {
  if (typeof window === "undefined") {
    console.log("🔧 Server-side: Returning default products")
    return [...defaultProducts]
  }

  try {
    // Always start with the complete default catalog
    console.log("✅ Initializing with complete product catalog:", defaultProducts.length)

    // Save to localStorage to ensure persistence
    localStorage.setItem("admin-products", JSON.stringify(defaultProducts))
    localStorage.setItem("products", JSON.stringify(defaultProducts))

    // Save metadata for debugging
    localStorage.setItem(
      "admin-products-meta",
      JSON.stringify({
        count: defaultProducts.length,
        lastUpdated: new Date().toISOString(),
        version: Date.now(),
        source: "complete-initialization",
      }),
    )

    return [...defaultProducts]
  } catch (error) {
    console.error("❌ Error initializing products:", error)
    // Always fallback to defaults
    return [...defaultProducts]
  }
}

// Get all products with guaranteed complete catalog
export function getAllProducts(): Product[] {
  if (typeof window === "undefined") {
    return [...defaultProducts]
  }

  try {
    // Always return the complete default catalog to prevent data loss
    return [...defaultProducts]
  } catch (error) {
    console.error("❌ Error getting all products:", error)
    return [...defaultProducts]
  }
}

// Force refresh with complete data restoration
export function forceRefreshProducts(): Product[] {
  if (typeof window === "undefined") {
    return [...defaultProducts]
  }

  try {
    console.log("🔄 Force refreshing products with complete catalog")

    // Clear potentially corrupted data
    localStorage.removeItem("admin-products")
    localStorage.removeItem("products")
    localStorage.removeItem("admin-products-meta")

    // Restore complete default catalog
    const restoredProducts = [...defaultProducts]

    // Save to both locations
    localStorage.setItem("admin-products", JSON.stringify(restoredProducts))
    localStorage.setItem("products", JSON.stringify(restoredProducts))

    // Save restoration metadata
    localStorage.setItem(
      "admin-products-meta",
      JSON.stringify({
        count: restoredProducts.length,
        lastUpdated: new Date().toISOString(),
        version: Date.now(),
        source: "force-refresh-complete",
        restoredFrom: "defaults",
      }),
    )

    // Trigger update events
    window.dispatchEvent(new CustomEvent("productsUpdated", { detail: restoredProducts }))
    window.dispatchEvent(new CustomEvent("adminProductsUpdated", { detail: restoredProducts }))

    console.log("✅ Products force refreshed successfully:", restoredProducts.length)
    return restoredProducts
  } catch (error) {
    console.error("❌ Error force refreshing products:", error)
    return [...defaultProducts]
  }
}

// Update products with validation and backup
export function updateProducts(newProducts: Product[]) {
  if (typeof window === "undefined") return

  try {
    if (!Array.isArray(newProducts)) {
      console.error("❌ Invalid products data: not an array")
      return
    }

    // Validate minimum product count to prevent data loss
    if (newProducts.length < 70) {
      console.warn("⚠️ Product count too low, refusing update:", newProducts.length)
      return
    }

    // Create backup before updating
    const existingProducts = localStorage.getItem("admin-products")
    if (existingProducts) {
      localStorage.setItem("admin-products-backup", existingProducts)
      localStorage.setItem("admin-products-backup-timestamp", new Date().toISOString())
    }

    // Save updated products
    localStorage.setItem("admin-products", JSON.stringify(newProducts))
    localStorage.setItem("products", JSON.stringify(newProducts))

    // Update metadata
    localStorage.setItem(
      "admin-products-meta",
      JSON.stringify({
        count: newProducts.length,
        lastUpdated: new Date().toISOString(),
        version: Date.now(),
        source: "update",
      }),
    )

    // Dispatch update events
    window.dispatchEvent(new CustomEvent("productsUpdated", { detail: newProducts }))
    window.dispatchEvent(new CustomEvent("adminProductsUpdated", { detail: newProducts }))

    console.log("✅ Products updated successfully:", newProducts.length)
  } catch (error) {
    console.error("❌ Error updating products:", error)
  }
}

// Get products from localStorage with fallback
export function getProducts(): Product[] {
  return getAllProducts()
}

// Export the default products for external use
export { defaultProducts as products }
